### ISSUE TITLE
Research api.github.com

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/GDET-Tremendous-Trio#1]
Make some command line “curl” requests to begin understanding how to make requests and what responses look like. Everyone should should understand this.

**Comment by gurnben** [comment]
You can find details on the GitHub API [here](https://developer.github.com/v3/)!

**Comment by gurnben** [comment]
See #7, we've elected to use a GitHub API Java Library, which will allow us to adapt to new API versions with less code alteration and interact with GitHub through a much more "friendly" api.
