### ISSUE TITLE
List Commit Comments

### ISSUE THREAD

**Issue by edwardstm** [CompassSoftware/GDET-Tremendous-Trio#17]
List comments on a commit. Depends on #12

**Comment by SupahSprinkle** [comment]
Having machine issues. I appear to not be able to locate a package via ubuntu.

**Comment by edwardstm** [comment]
I am not having your issue; would like to take a look at your system
configuration in the morning. It's possible that something is wrong with
the pom.xml, but I would expect that to produce an issue for me as well.

**Comment by gurnben** [comment]
Addressed in #44
