### ISSUE TITLE
Set up project build system.

### ISSUE THREAD

**Issue by edwardstm** [CompassSoftware/GDET-Tremendous-Trio#5]
Add build system (Maven).
Also select and integrate a JSON parsing library for Java from the Maven repository.

Resolved by #2

**Comment by edwardstm** [comment]
Per discussion, initial PR implements Google's `gson 2.8.5`. Also considered was a more fully-featured Java wrapper for the GitHub API, `org.kohsuke.github-api`. Some worry was expressed that using this wrapper might present issues for future project maintainers were it to be unmaintained following major changes the GitHub API.

**Comment by gurnben** [comment]
This was resolved by #2, which is now merged!  We should be good to go, pending further debate on the github-api integration in Java!
