### ISSUE TITLE
Load Configuration from File

### ISSUE THREAD

**Issue by edwardstm** [CompassSoftware/GDET-Tremendous-Trio#9]
We should load user configuration (OAuth tokens, etc) from a file. This file should be added to `.gitignore` if it is to exist within the local repo path. Note that `org.kohsuke.github-api` currently reads this file from `~/.github`. This is fine, but respecting the `${XDG_CONFIG_HOME}` spec for dotfile location sounds like a good idea.

**Comment by SupahSprinkle** [comment]
The API wrapper loads

**Comment by edwardstm** [comment]
Agreed. It would be best if `${XDG_CONFIG_HOME}` suppoer were to be fixed upstream. I'll make a feature request there.

**Comment by edwardstm** [comment]
[Upstream issue](https://github.com/kohsuke/github-api/issues/471) for XDG Base Directory Specification created.
